name: elector
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  get: ^4.6.5
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.0.15
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5+3
  lottie: ^1.3.0
  carousel_slider: ^4.1.1
  firebase_core: ^2.0.0
  cloud_firestore: ^4.2.0
  firebase_auth: ^4.2.0
  firebase_storage: ^11.0.0
  local_auth: ^2.1.2
  flutter_secure_storage: ^6.0.0
  dio: ^4.0.6
  intl: ^0.17.0
  charts_flutter: ^0.12.0
  sizer: ^2.0.15



dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
