// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIcdY5Rc7W31rogZ3bF--fTYxyzrhWdCI',
    appId: '1:941038960713:web:19e73dc739f5688df7ff98',
    messagingSenderId: '941038960713',
    projectId: 'elector-6352c',
    authDomain: 'elector-6352c.firebaseapp.com',
    storageBucket: 'elector-6352c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8l-POAo6awuC9Z5I28t9F-fuCOqEyTzI',
    appId: '1:941038960713:android:8dcf075ad542f21ff7ff98',
    messagingSenderId: '941038960713',
    projectId: 'elector-6352c',
    storageBucket: 'elector-6352c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdLLH7HxCA370lLaFhakm3BuPeemWem9E',
    appId: '1:941038960713:ios:555cc09079625a25f7ff98',
    messagingSenderId: '941038960713',
    projectId: 'elector-6352c',
    storageBucket: 'elector-6352c.appspot.com',
    iosClientId: '941038960713-e217v85t27fk3t8dvfult09r5il8mlmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.elector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdLLH7HxCA370lLaFhakm3BuPeemWem9E',
    appId: '1:941038960713:ios:555cc09079625a25f7ff98',
    messagingSenderId: '941038960713',
    projectId: 'elector-6352c',
    storageBucket: 'elector-6352c.appspot.com',
    iosClientId: '941038960713-e217v85t27fk3t8dvfult09r5il8mlmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.elector',
  );
}
